# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Storage.GetCookies do
  @moduledoc """
  Command struct for `storage.getCookies`.
  """

  defstruct [:filter, :partition]

  defimpl Bibbidi.Encodable do
    def method(_), do: "storage.getCookies"

    def params(cmd) do
      optional = [
        {:filter, cmd.filter},
        {:partition, cmd.partition}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
