# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Storage.SetCookie do
  @moduledoc """
  Command struct for `storage.setCookie`.
  """

  @enforce_keys [:cookie]
  defstruct [:cookie, :partition]

  defimpl Bibbidi.Encodable do
    def method(_), do: "storage.setCookie"

    def params(cmd) do
      optional = [
        {:partition, cmd.partition}
      ]

      Enum.reduce(optional, %{cookie: cmd.cookie}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
