defmodule Mix.Tasks.Bibbidi.Gen.Workflow do
  @shortdoc "Generate a workflow runner for BiDi command orchestration"

  @moduledoc """
  Generates a Multi-style workflow builder and sequential runner
  into your project.

      mix bibbidi.gen.workflow

  This generates:

  - `lib/<app>/bibbidi/op.ex` — pipeline builder
  - `lib/<app>/bibbidi/operation.ex` — execution record struct
  - `lib/<app>/bibbidi/runner.ex` — sequential runner
  - `test/<app>/bibbidi/runner_test.exs` — test scaffold

  The generated code calls `Bibbidi.Connection.execute/2` for
  leaf commands and accumulates results in a named map.

  This code is yours to own and modify. If you're using a workflow
  engine like Runic or Reactor, consider using `bibbidi_runic` or
  writing a thin adapter instead.
  """

  use Igniter.Mix.Task

  @impl Igniter.Mix.Task
  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{}
  end

  @impl Igniter.Mix.Task
  def igniter(igniter) do
    prefix = Igniter.Project.Module.module_name_prefix(igniter)

    igniter
    |> generate_op(prefix)
    |> generate_operation(prefix)
    |> generate_runner(prefix)
    |> generate_runner_test(prefix)
  end

  defp generate_op(igniter, prefix) do
    module = Module.concat([prefix, Bibbidi, Op])

    content = ~s'''
    defmodule #{inspect(module)} do
      @moduledoc """
      Multi-style pipeline builder for composing BiDi commands.

      Generated by `mix bibbidi.gen.workflow`. This code is yours to modify.

      ## Usage

          alias #{inspect(prefix)}.Bibbidi.Op
          alias Bibbidi.Commands.BrowsingContext

          op =
            Op.new()
            |> Op.send(:navigate, %BrowsingContext.Navigate{
              context: ctx, url: "https://example.com", wait: "complete"
            })
            |> Op.send(:tree, %BrowsingContext.GetTree{})

          {:ok, results, operation} = #{inspect(prefix)}.Bibbidi.Runner.execute(conn, op)
      """

      defstruct steps: []

      @type t :: %__MODULE__{steps: [{atom(), step()}]}

      @type step ::
              {:send, Bibbidi.Encodable.t()}
              | {:send_fn, (results() -> {:send, Bibbidi.Encodable.t()} | {:ok, term()} | {:error, term()})}
              | {:run, (GenServer.server(), results(), keyword() -> {:ok, term()} | {:error, term()})}
              | {:branch_fn, (results() -> {:send, Bibbidi.Encodable.t()} | {:ok, term()} | {:error, term()})}

      @type results :: %{atom() => {:ok, term()} | {:error, term()}}

      @doc "Create a new empty pipeline."
      @spec new() :: t()
      def new, do: %__MODULE__{}

      @doc """
      Add a command to send over the wire.

      When `command_or_fn` is an `Encodable` struct, it is sent directly.
      When it is a function, it receives the accumulated results map and
      must return `{:send, command}`, `{:ok, value}`, or `{:error, reason}`.
      """
      @spec send(t(), atom(), Bibbidi.Encodable.t() | (results() -> term())) :: t()
      def send(%__MODULE__{} = op, name, %{__struct__: _} = command) do
        validate_name!(op, name)
        %{op | steps: op.steps ++ [{name, {:send, command}}]}
      end

      def send(%__MODULE__{} = op, name, fun) when is_function(fun, 1) do
        validate_name!(op, name)
        %{op | steps: op.steps ++ [{name, {:send_fn, fun}}]}
      end

      @doc """
      Add an arbitrary step that receives the connection and results.

      The function should return `{:ok, value}` or `{:error, reason}`.
      Use this for operations like polling/waiting that need direct
      connection access.
      """
      @spec run(t(), atom(), (GenServer.server(), results(), keyword() -> term())) :: t()
      def run(%__MODULE__{} = op, name, fun) when is_function(fun, 3) do
        validate_name!(op, name)
        %{op | steps: op.steps ++ [{name, {:run, fun}}]}
      end

      @doc """
      Add a branching step that decides what to do based on previous results.

      The function receives the accumulated results and must return
      `{:send, command}`, `{:ok, value}`, or `{:error, reason}`.
      """
      @spec branch(t(), atom(), (results() -> term())) :: t()
      def branch(%__MODULE__{} = op, name, fun) when is_function(fun, 1) do
        validate_name!(op, name)
        %{op | steps: op.steps ++ [{name, {:branch_fn, fun}}]}
      end

      defp validate_name!(%__MODULE__{steps: steps}, name) do
        if List.keymember?(steps, name, 0) do
          raise ArgumentError, "step name \#{inspect(name)} is already used in this pipeline"
        end
      end
    end
    '''

    Igniter.create_new_file(igniter, Igniter.Project.Module.proper_location(igniter, module), content)
  end

  defp generate_operation(igniter, prefix) do
    module = Module.concat([prefix, Bibbidi, Operation])

    content = ~s'''
    defmodule #{inspect(module)} do
      @moduledoc """
      Execution record for a workflow pipeline.

      Generated by `mix bibbidi.gen.workflow`. This code is yours to modify.

      Tracks every wire command sent, its result, and the accumulated
      named step outcomes.
      """

      @type step :: %{
              name: atom(),
              command: Bibbidi.Encodable.t() | nil,
              result: {:ok, term()} | {:error, term()},
              at: integer()
            }

      @type t :: %__MODULE__{
              id: String.t(),
              steps: [step()],
              results: %{atom() => {:ok, term()} | {:error, term()}},
              started_at: integer(),
              ended_at: integer() | nil,
              status: :running | :completed | :failed,
              error: term() | nil
            }

      defstruct [
        :id,
        :started_at,
        :ended_at,
        :error,
        steps: [],
        results: %{},
        status: :running
      ]
    end
    '''

    Igniter.create_new_file(igniter, Igniter.Project.Module.proper_location(igniter, module), content)
  end

  defp generate_runner(igniter, prefix) do
    module = Module.concat([prefix, Bibbidi, Runner])
    op_module = Module.concat([prefix, Bibbidi, Op])
    operation_module = Module.concat([prefix, Bibbidi, Operation])

    content = ~s'''
    defmodule #{inspect(module)} do
      @moduledoc """
      Sequential runner for Op pipelines.

      Generated by `mix bibbidi.gen.workflow`. This code is yours to modify.

      Calls `Bibbidi.Connection.execute/2` for each leaf command and
      accumulates named results.
      """

      alias #{inspect(op_module)}, as: Op
      alias #{inspect(operation_module)}, as: Operation

      @doc """
      Execute a pipeline, returning `{:ok, results, operation}` or
      `{:error, {step_name, reason}, operation}`.
      """
      @spec execute(GenServer.server(), Op.t(), keyword()) ::
              {:ok, Op.results(), Operation.t()} | {:error, {atom(), term()}, Operation.t()}
      def execute(conn, %Op{} = op, opts \\\\ []) do
        operation = %Operation{
          id: generate_id(),
          started_at: System.monotonic_time(:millisecond)
        }

        run_pipeline(conn, op.steps, %{}, operation, opts)
      end

      defp run_pipeline(_conn, [], results, operation, _opts) do
        {:ok, results, finalize(operation, results)}
      end

      defp run_pipeline(conn, [{name, {:send, cmd}} | rest], results, operation, opts) do
        case Bibbidi.Connection.execute(conn, cmd, opts) do
          {:ok, response} ->
            step = %{name: name, command: cmd, result: {:ok, response}, at: now()}
            operation = record_step(operation, step)
            run_pipeline(conn, rest, Map.put(results, name, {:ok, response}), operation, opts)

          {:error, reason} ->
            step = %{name: name, command: cmd, result: {:error, reason}, at: now()}
            operation = record_step(operation, step)
            {:error, {name, reason}, finalize_failed(operation, results, name, reason)}
        end
      end

      defp run_pipeline(conn, [{name, {:send_fn, fun}} | rest], results, operation, opts) do
        case fun.(results) do
          {:send, cmd} ->
            run_pipeline(conn, [{name, {:send, cmd}} | rest], results, operation, opts)

          {:ok, value} ->
            step = %{name: name, command: nil, result: {:ok, value}, at: now()}
            operation = record_step(operation, step)
            run_pipeline(conn, rest, Map.put(results, name, {:ok, value}), operation, opts)

          {:error, reason} ->
            step = %{name: name, command: nil, result: {:error, reason}, at: now()}
            operation = record_step(operation, step)
            {:error, {name, reason}, finalize_failed(operation, results, name, reason)}
        end
      end

      defp run_pipeline(conn, [{name, {:run, fun}} | rest], results, operation, opts) do
        case fun.(conn, results, opts) do
          {:ok, value} ->
            step = %{name: name, command: nil, result: {:ok, value}, at: now()}
            operation = record_step(operation, step)
            run_pipeline(conn, rest, Map.put(results, name, {:ok, value}), operation, opts)

          {:error, reason} ->
            step = %{name: name, command: nil, result: {:error, reason}, at: now()}
            operation = record_step(operation, step)
            {:error, {name, reason}, finalize_failed(operation, results, name, reason)}
        end
      end

      defp run_pipeline(conn, [{name, {:branch_fn, fun}} | rest], results, operation, opts) do
        case fun.(results) do
          {:send, cmd} ->
            case Bibbidi.Connection.execute(conn, cmd, opts) do
              {:ok, response} ->
                step = %{name: name, command: cmd, result: {:ok, response}, at: now()}
                operation = record_step(operation, step)
                run_pipeline(conn, rest, Map.put(results, name, {:ok, response}), operation, opts)

              {:error, reason} ->
                step = %{name: name, command: cmd, result: {:error, reason}, at: now()}
                operation = record_step(operation, step)
                {:error, {name, reason}, finalize_failed(operation, results, name, reason)}
            end

          {:ok, value} ->
            step = %{name: name, command: nil, result: {:ok, value}, at: now()}
            operation = record_step(operation, step)
            run_pipeline(conn, rest, Map.put(results, name, {:ok, value}), operation, opts)

          {:error, reason} ->
            step = %{name: name, command: nil, result: {:error, reason}, at: now()}
            operation = record_step(operation, step)
            {:error, {name, reason}, finalize_failed(operation, results, name, reason)}
        end
      end

      defp record_step(operation, step) do
        %{operation | steps: operation.steps ++ [step]}
      end

      defp finalize(operation, results) do
        %{operation | status: :completed, results: results, ended_at: now()}
      end

      defp finalize_failed(operation, results, name, reason) do
        %{operation | status: :failed, results: results, error: {name, reason}, ended_at: now()}
      end

      defp now, do: System.monotonic_time(:millisecond)

      defp generate_id do
        "op_" <> Base.url_encode64(:crypto.strong_rand_bytes(9), padding: false)
      end
    end
    '''

    Igniter.create_new_file(igniter, Igniter.Project.Module.proper_location(igniter, module), content)
  end

  defp generate_runner_test(igniter, prefix) do
    module = Module.concat([prefix, Bibbidi, RunnerTest])
    op_module = Module.concat([prefix, Bibbidi, Op])
    runner_module = Module.concat([prefix, Bibbidi, Runner])

    content = ~s'''
    defmodule #{inspect(module)} do
      use ExUnit.Case, async: true

      alias Bibbidi.Connection
      alias Bibbidi.Commands.BrowsingContext
      alias #{inspect(op_module)}, as: Op
      alias #{inspect(runner_module)}, as: Runner

      setup do
        {:ok, conn} =
          Connection.start_link(
            url: "ws://localhost:1234",
            transport: Bibbidi.MockTransport,
            transport_opts: [owner: self()]
          )

        %{conn: conn}
      end

      defp mock_reply(conn, result) do
        assert_receive {:mock_transport_send, json}
        decoded = JSON.decode!(json)

        send(
          conn,
          {:mock_transport_receive,
           [{:text, JSON.encode!(%{id: decoded["id"], result: result})}]}
        )

        decoded
      end

      defp mock_error(conn, error, message) do
        assert_receive {:mock_transport_send, json}
        decoded = JSON.decode!(json)

        send(
          conn,
          {:mock_transport_receive,
           [{:text, JSON.encode!(%{id: decoded["id"], error: error, message: message})}]}
        )

        decoded
      end

      describe "Op builder" do
        test "rejects duplicate step names" do
          op = Op.new() |> Op.send(:nav, %BrowsingContext.Activate{context: "c"})

          assert_raise ArgumentError, ~r/already used/, fn ->
            Op.send(op, :nav, %BrowsingContext.Activate{context: "c"})
          end
        end
      end

      describe "Runner.execute/3 with static sends" do
        test "runs a single send step", %{conn: conn} do
          op =
            Op.new()
            |> Op.send(:activate, %BrowsingContext.Activate{context: "ctx-1"})

          task = Task.async(fn -> Runner.execute(conn, op) end)

          decoded = mock_reply(conn, %{})
          assert decoded["method"] == "browsingContext.activate"

          assert {:ok, results, operation} = Task.await(task)
          assert {:ok, %{}} = results[:activate]
          assert operation.status == :completed
          assert length(operation.steps) == 1
        end

        test "runs multiple sends in order", %{conn: conn} do
          op =
            Op.new()
            |> Op.send(:nav, %BrowsingContext.Navigate{
              context: "ctx-1", url: "https://example.com"
            })
            |> Op.send(:tree, %BrowsingContext.GetTree{})

          task = Task.async(fn -> Runner.execute(conn, op) end)

          d1 = mock_reply(conn, %{navigation: "nav-1"})
          assert d1["method"] == "browsingContext.navigate"

          d2 = mock_reply(conn, %{contexts: []})
          assert d2["method"] == "browsingContext.getTree"

          assert {:ok, results, operation} = Task.await(task)
          assert {:ok, %{"navigation" => "nav-1"}} = results[:nav]
          assert {:ok, %{"contexts" => []}} = results[:tree]
          assert operation.status == :completed
          assert length(operation.steps) == 2
        end

        test "stops on first error", %{conn: conn} do
          op =
            Op.new()
            |> Op.send(:nav, %BrowsingContext.Navigate{
              context: "ctx-1", url: "https://bad.com"
            })
            |> Op.send(:tree, %BrowsingContext.GetTree{})

          task = Task.async(fn -> Runner.execute(conn, op) end)

          mock_error(conn, "navigation failed", "bad url")

          assert {:error, {:nav, _reason}, operation} = Task.await(task)
          assert operation.status == :failed
          assert length(operation.steps) == 1
        end
      end

      describe "Runner.execute/3 with branch" do
        test "branch can send a command based on results", %{conn: conn} do
          op =
            Op.new()
            |> Op.send(:nav, %BrowsingContext.Navigate{
              context: "ctx-1", url: "https://example.com"
            })
            |> Op.branch(:maybe_tree, fn
              %{nav: {:ok, _}} ->
                {:send, %BrowsingContext.GetTree{}}
              %{nav: {:error, _}} ->
                {:error, :skipped}
            end)

          task = Task.async(fn -> Runner.execute(conn, op) end)

          mock_reply(conn, %{navigation: "nav-1"})
          mock_reply(conn, %{contexts: []})

          assert {:ok, results, _op} = Task.await(task)
          assert {:ok, %{"contexts" => []}} = results[:maybe_tree]
        end

        test "branch can short-circuit with ok", %{conn: conn} do
          op =
            Op.new()
            |> Op.branch(:decision, fn _ -> {:ok, :done} end)

          task = Task.async(fn -> Runner.execute(conn, op) end)

          assert {:ok, results, _op} = Task.await(task)
          assert results[:decision] == {:ok, :done}
        end

        test "branch can short-circuit with error", %{conn: conn} do
          op =
            Op.new()
            |> Op.branch(:decision, fn _ -> {:error, :nope} end)

          task = Task.async(fn -> Runner.execute(conn, op) end)

          assert {:error, {:decision, :nope}, _op} = Task.await(task)
        end
      end

      describe "operation metadata" do
        test "generates unique IDs", %{conn: conn} do
          op = Op.new() |> Op.send(:a, %BrowsingContext.Activate{context: "c"})

          task1 = Task.async(fn -> Runner.execute(conn, op) end)
          mock_reply(conn, %{})
          {:ok, _, op1} = Task.await(task1)

          task2 = Task.async(fn -> Runner.execute(conn, op) end)
          mock_reply(conn, %{})
          {:ok, _, op2} = Task.await(task2)

          assert op1.id != op2.id
          assert String.starts_with?(op1.id, "op_")
        end

        test "records timing", %{conn: conn} do
          op = Op.new() |> Op.send(:a, %BrowsingContext.Activate{context: "c"})

          task = Task.async(fn -> Runner.execute(conn, op) end)
          mock_reply(conn, %{})
          {:ok, _, operation} = Task.await(task)

          assert operation.started_at <= operation.ended_at
        end
      end
    end
    '''

    test_path =
      module
      |> Module.split()
      |> Enum.map(&Macro.underscore/1)
      |> then(fn parts -> Path.join(["test" | parts]) <> ".exs" end)

    Igniter.create_new_file(igniter, test_path, content)
  end
end
