# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Session.End do
  @moduledoc """
  Command struct for `session.end`.
  """

  defstruct []

  defimpl Bibbidi.Encodable do
    def method(_), do: "session.end"

    def params(_cmd), do: %{}
  end
end
