# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Session.New do
  @moduledoc """
  Command struct for `session.new`.
  """

  @enforce_keys [:capabilities]
  defstruct [:capabilities]

  defimpl Bibbidi.Encodable do
    def method(_), do: "session.new"

    def params(cmd), do: %{capabilities: cmd.capabilities}
  end
end
