# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Session.Status do
  @moduledoc """
  Command struct for `session.status`.
  """

  defstruct []

  defimpl Bibbidi.Encodable do
    def method(_), do: "session.status"

    def params(_cmd), do: %{}
  end
end
