# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Session.Subscribe do
  @moduledoc """
  Command struct for `session.subscribe`.
  """

  @enforce_keys [:events]
  defstruct [:events, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "session.subscribe"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{events: cmd.events}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
