# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Session.Unsubscribe do
  @moduledoc """
  Command struct for `session.unsubscribe`.
  """

  defstruct []

  defimpl Bibbidi.Encodable do
    def method(_), do: "session.unsubscribe"

    def params(_cmd), do: %{}
  end
end
