# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Input.FileDialogOpened do
  @moduledoc """
  Command struct for `input.fileDialogOpened`.
  """

  @enforce_keys [:context, :multiple]
  defstruct [:context, :multiple, :user_context, :element]

  defimpl Bibbidi.Encodable do
    def method(_), do: "input.fileDialogOpened"

    def params(cmd) do
      optional = [
        {:userContext, cmd.user_context},
        {:element, cmd.element}
      ]

      Enum.reduce(optional, %{context: cmd.context, multiple: cmd.multiple}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
