# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Input.PerformActions do
  @moduledoc """
  Command struct for `input.performActions`.
  """

  @enforce_keys [:context, :actions]
  defstruct [:context, :actions]

  defimpl Bibbidi.Encodable do
    def method(_), do: "input.performActions"

    def params(cmd), do: %{context: cmd.context, actions: cmd.actions}
  end
end
