# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Input.ReleaseActions do
  @moduledoc """
  Command struct for `input.releaseActions`.
  """

  @enforce_keys [:context]
  defstruct [:context]

  defimpl Bibbidi.Encodable do
    def method(_), do: "input.releaseActions"

    def params(cmd), do: %{context: cmd.context}
  end
end
