# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Input.SetFiles do
  @moduledoc """
  Command struct for `input.setFiles`.
  """

  @enforce_keys [:context, :element, :files]
  defstruct [:context, :element, :files]

  defimpl Bibbidi.Encodable do
    def method(_), do: "input.setFiles"

    def params(cmd), do: %{context: cmd.context, element: cmd.element, files: cmd.files}
  end
end
