# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.BrowsingContext do
  @moduledoc """
  Events for the `browsingContext` module of the WebDriver BiDi protocol.
  """

  @doc "Returns all event method names for this module."
  @spec events() :: [String.t()]
  def events do
    [
      "browsingContext.contextCreated",
      "browsingContext.contextDestroyed",
      "browsingContext.navigationStarted",
      "browsingContext.fragmentNavigated",
      "browsingContext.historyUpdated",
      "browsingContext.domContentLoaded",
      "browsingContext.load",
      "browsingContext.downloadWillBegin",
      "browsingContext.downloadEnd",
      "browsingContext.navigationAborted",
      "browsingContext.navigationCommitted",
      "browsingContext.navigationFailed",
      "browsingContext.userPromptClosed",
      "browsingContext.userPromptOpened"
    ]
  end

  @doc """
  Event: `browsingContext.contextCreated`

  Params type: `browsingContext.Info`
  """
  def context_created, do: "browsingContext.contextCreated"

  @doc """
  Event: `browsingContext.contextDestroyed`

  Params type: `browsingContext.Info`
  """
  def context_destroyed, do: "browsingContext.contextDestroyed"

  @doc """
  Event: `browsingContext.navigationStarted`

  Params type: `browsingContext.NavigationInfo`
  """
  def navigation_started, do: "browsingContext.navigationStarted"

  @doc """
  Event: `browsingContext.fragmentNavigated`

  Params type: `browsingContext.NavigationInfo`
  """
  def fragment_navigated, do: "browsingContext.fragmentNavigated"

  @doc """
  Event: `browsingContext.historyUpdated`

  Params type: `browsingContext.HistoryUpdatedParameters`
  """
  def history_updated, do: "browsingContext.historyUpdated"

  @doc """
  Event: `browsingContext.domContentLoaded`

  Params type: `browsingContext.NavigationInfo`
  """
  def dom_content_loaded, do: "browsingContext.domContentLoaded"

  @doc """
  Event: `browsingContext.load`

  Params type: `browsingContext.NavigationInfo`
  """
  def load, do: "browsingContext.load"

  @doc """
  Event: `browsingContext.downloadWillBegin`

  Params type: `browsingContext.DownloadWillBeginParams`
  """
  def download_will_begin, do: "browsingContext.downloadWillBegin"

  @doc """
  Event: `browsingContext.downloadEnd`

  Params type: `browsingContext.DownloadEndParams`
  """
  def download_end, do: "browsingContext.downloadEnd"

  @doc """
  Event: `browsingContext.navigationAborted`

  Params type: `browsingContext.NavigationInfo`
  """
  def navigation_aborted, do: "browsingContext.navigationAborted"

  @doc """
  Event: `browsingContext.navigationCommitted`

  Params type: `browsingContext.NavigationInfo`
  """
  def navigation_committed, do: "browsingContext.navigationCommitted"

  @doc """
  Event: `browsingContext.navigationFailed`

  Params type: `browsingContext.NavigationInfo`
  """
  def navigation_failed, do: "browsingContext.navigationFailed"

  @doc """
  Event: `browsingContext.userPromptClosed`

  Params type: `browsingContext.UserPromptClosedParameters`
  """
  def user_prompt_closed, do: "browsingContext.userPromptClosed"

  @doc """
  Event: `browsingContext.userPromptOpened`

  Params type: `browsingContext.UserPromptOpenedParameters`
  """
  def user_prompt_opened, do: "browsingContext.userPromptOpened"
end
