# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Input do
  @moduledoc """
  Events for the `input` module of the WebDriver BiDi protocol.
  """

  @doc "Returns all event method names for this module."
  @spec events() :: [String.t()]
  def events do
    [
      "input.fileDialogOpened"
    ]
  end

  @doc """
  Event: `input.fileDialogOpened`

  Params type: `input.FileDialogInfo`
  """
  def file_dialog_opened, do: "input.fileDialogOpened"
end
