# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Log do
  @moduledoc """
  Events for the `log` module of the WebDriver BiDi protocol.
  """

  @doc "Returns all event method names for this module."
  @spec events() :: [String.t()]
  def events do
    [
      "log.entryAdded"
    ]
  end

  @doc """
  Event: `log.entryAdded`

  Params type: `log.Entry`
  """
  def entry_added, do: "log.entryAdded"
end
