# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Network do
  @moduledoc """
  Events for the `network` module of the WebDriver BiDi protocol.
  """

  @doc "Returns all event method names for this module."
  @spec events() :: [String.t()]
  def events do
    [
      "network.authRequired",
      "network.beforeRequestSent",
      "network.fetchError",
      "network.responseCompleted",
      "network.responseStarted"
    ]
  end

  @doc """
  Event: `network.authRequired`

  Params type: `network.AuthRequiredParameters`
  """
  def auth_required, do: "network.authRequired"

  @doc """
  Event: `network.beforeRequestSent`

  Params type: `network.BeforeRequestSentParameters`
  """
  def before_request_sent, do: "network.beforeRequestSent"

  @doc """
  Event: `network.fetchError`

  Params type: `network.FetchErrorParameters`
  """
  def fetch_error, do: "network.fetchError"

  @doc """
  Event: `network.responseCompleted`

  Params type: `network.ResponseCompletedParameters`
  """
  def response_completed, do: "network.responseCompleted"

  @doc """
  Event: `network.responseStarted`

  Params type: `network.ResponseStartedParameters`
  """
  def response_started, do: "network.responseStarted"
end
