# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Script do
  @moduledoc """
  Events for the `script` module of the WebDriver BiDi protocol.
  """

  @doc "Returns all event method names for this module."
  @spec events() :: [String.t()]
  def events do
    [
      "script.message",
      "script.realmCreated",
      "script.realmDestroyed"
    ]
  end

  @doc """
  Event: `script.message`

  Params type: `script.MessageParameters`
  """
  def message, do: "script.message"

  @doc """
  Event: `script.realmCreated`

  Params type: `script.RealmInfo`
  """
  def realm_created, do: "script.realmCreated"

  @doc """
  Event: `script.realmDestroyed`

  Params type: `script.RealmDestroyedParameters`
  """
  def realm_destroyed, do: "script.realmDestroyed"
end
