# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.WebExtension.Install do
  @moduledoc """
  Command struct for `webExtension.install`.
  """

  @enforce_keys [:extension_data]
  defstruct [:extension_data]

  defimpl Bibbidi.Encodable do
    def method(_), do: "webExtension.install"

    def params(cmd), do: %{extensionData: cmd.extension_data}
  end
end
