# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.WebExtension.Uninstall do
  @moduledoc """
  Command struct for `webExtension.uninstall`.
  """

  @enforce_keys [:extension]
  defstruct [:extension]

  defimpl Bibbidi.Encodable do
    def method(_), do: "webExtension.uninstall"

    def params(cmd), do: %{extension: cmd.extension}
  end
end
