defmodule Bibbidi.CDDL.Generator do
  @moduledoc false

  alias Bibbidi.CDDL.Parser

  @modules ~w(browsingContext script session browser network log storage input emulation webExtension)

  @doc """
  Builds an `%Igniter{}` with all generated types, events, and command modules.

  Returns the igniter struct — the caller decides whether to apply or dry-run.
  """
  @spec run(Igniter.t()) :: Igniter.t()
  def run(igniter) do
    {:ok, remote_rules} = Parser.parse_file("priv/cddl/remote.cddl")
    {:ok, local_rules} = Parser.parse_file("priv/cddl/local.cddl")

    all_rules = remote_rules ++ local_rules
    grouped = group_by_module(all_rules)

    Enum.reduce(@modules, igniter, fn mod, igniter ->
      rules = Map.get(grouped, mod, [])

      igniter
      |> maybe_generate_types_module(mod, rules)
      |> maybe_generate_events_module(mod, rules, local_rules)
      |> maybe_generate_command_modules(mod, remote_rules, all_rules)
    end)
  end

  defp group_by_module(rules) do
    rules
    |> Enum.filter(fn {name, _} -> String.contains?(name, ".") end)
    |> Enum.group_by(fn {name, _} -> name |> String.split(".") |> hd() end)
  end

  defp maybe_generate_types_module(igniter, mod, rules) do
    types = extract_types(rules)
    if types == [], do: igniter, else: generate_types_module(igniter, mod, types)
  end

  defp generate_types_module(igniter, mod, types) do
    snake = to_snake(mod)
    camel = to_module_name(mod)

    type_defs =
      types
      |> Enum.map(fn {name, def} -> generate_type(name, def) end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq_by(fn line -> line |> String.split("::") |> hd() |> String.trim() end)
      |> Enum.join("\n\n")

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Types.#{camel} do
      @moduledoc \"\"\"
      Type definitions for the `#{mod}` module of the WebDriver BiDi protocol.
      \"\"\"

    #{type_defs}
    end
    """

    path = "lib/bibbidi/types/#{snake}.ex"

    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  defp maybe_generate_events_module(igniter, mod, _rules, local_rules) do
    events = extract_events(mod, local_rules)
    if events == [], do: igniter, else: generate_events_module(igniter, mod, events)
  end

  defp generate_events_module(igniter, mod, events) do
    snake = to_snake(mod)
    camel = to_module_name(mod)

    event_list =
      events
      |> Enum.map(fn {method, _params_ref} -> ~s("#{method}") end)
      |> Enum.join(",\n      ")

    event_functions =
      events
      |> Enum.map(fn {method, params_ref} ->
        fun_name = method |> String.split(".") |> List.last() |> to_snake()

        """
          @doc \"\"\"
          Event: `#{method}`

          Params type: `#{params_ref || "none"}`
          \"\"\"
          def #{fun_name}, do: "#{method}"
        """
      end)
      |> Enum.join("\n")

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Events.#{camel} do
      @moduledoc \"\"\"
      Events for the `#{mod}` module of the WebDriver BiDi protocol.
      \"\"\"

      @doc "Returns all event method names for this module."
      @spec events() :: [String.t()]
      def events do
        [
          #{event_list}
        ]
      end

    #{event_functions}end
    """

    path = "lib/bibbidi/events/#{snake}.ex"

    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  defp extract_types(rules) do
    Enum.reject(rules, fn {name, def} ->
      # Skip command definitions (groups with method + params) and top-level dispatchers
      is_command_def?(def) or is_event_def?(def) or
        String.ends_with?(name, "Command") or String.ends_with?(name, "Event")
    end)
  end

  defp extract_events(mod, local_rules) do
    local_rules
    |> Enum.filter(fn {name, def} ->
      String.starts_with?(name, mod <> ".") and is_event_def?(def)
    end)
    |> Enum.map(fn {_name, {:group, members}} ->
      method =
        Enum.find_value(members, fn
          {:required, "method", {:string, m}} -> m
          _ -> nil
        end)

      params_ref =
        Enum.find_value(members, fn
          {:required, "params", {:ref, r}} -> r
          _ -> nil
        end)

      {method, params_ref}
    end)
    |> Enum.reject(fn {method, _} -> is_nil(method) end)
  end

  # ── Command struct generation ─────────────────────────────────────

  defp maybe_generate_command_modules(igniter, mod, remote_rules, all_rules) do
    commands = extract_commands(mod, remote_rules)
    if commands == [], do: igniter, else: generate_command_modules(igniter, mod, commands, all_rules)
  end

  defp extract_commands(mod, remote_rules) do
    remote_rules
    |> Enum.filter(fn {name, def} ->
      String.starts_with?(name, mod <> ".") and is_command_def?(def)
    end)
    |> Enum.map(fn {name, {:group, members}} ->
      command_name = name |> String.split(".") |> List.last()

      method =
        Enum.find_value(members, fn
          {:required, "method", {:string, m}} -> m
          _ -> nil
        end)

      params_ref =
        Enum.find_value(members, fn
          {:required, "params", {:ref, r}} -> r
          _ -> nil
        end)

      {command_name, method, params_ref}
    end)
    |> Enum.reject(fn {_, method, _} -> is_nil(method) end)
  end

  defp generate_command_modules(igniter, mod, commands, all_rules) do
    Enum.reduce(commands, igniter, fn {command_name, method, params_ref}, igniter ->
      generate_command_module(igniter, mod, command_name, method, params_ref, all_rules)
    end)
  end

  defp generate_command_module(igniter, mod, command_name, method, params_ref, all_rules) do
    snake_mod = to_snake(mod)
    camel_mod = to_module_name(mod)
    command_snake = to_snake(command_name)

    fields = resolve_command_fields(params_ref, all_rules)

    required = Enum.filter(fields, fn {_, _, req} -> req == :required end)
    optional = Enum.filter(fields, fn {_, _, req} -> req == :optional end)
    all_fields = required ++ optional

    enforce_keys_line =
      case required do
        [] ->
          ""

        _ ->
          keys = Enum.map_join(required, ", ", fn {_, elixir, _} -> ":#{elixir}" end)
          "@enforce_keys [#{keys}]\n  "
      end

    struct_fields = Enum.map_join(all_fields, ", ", fn {_, elixir, _} -> ":#{elixir}" end)
    params_body = generate_params_body(required, optional)

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Commands.#{camel_mod}.#{command_name} do
      @moduledoc \"\"\"
      Command struct for `#{method}`.
      \"\"\"

      #{enforce_keys_line}defstruct [#{struct_fields}]

      defimpl Bibbidi.Encodable do
        def method(_), do: "#{method}"

    #{params_body}
      end
    end
    """

    path = "lib/bibbidi/commands/#{snake_mod}/#{command_snake}.ex"
    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  defp resolve_command_fields(nil, _all_rules), do: []
  defp resolve_command_fields("EmptyParams", _all_rules), do: []

  defp resolve_command_fields(ref, all_rules) do
    case List.keyfind(all_rules, ref, 0) do
      {^ref, {:map, content}} ->
        extract_field_defs_from_map(content)

      {^ref, {:group, members}} ->
        extract_field_defs(members)

      {^ref, {:choice, alternatives}} ->
        # For choice types, merge fields from all alternatives (all optional)
        resolve_choice_fields(alternatives, all_rules)

      _ ->
        []
    end
  end

  defp extract_field_defs_from_map(content) do
    Enum.flat_map(content, fn
      {:fields, fields} -> extract_field_defs(fields)
      {:group_choice, groups} -> extract_field_defs_from_group_choice(groups)
      _ -> []
    end)
  end

  defp extract_field_defs_from_group_choice(groups) do
    # For group choices inside maps (e.g. coordinates // error),
    # include all fields as optional since only one branch is used at a time
    Enum.flat_map(groups, fn
      {:fields, fields} ->
        Enum.flat_map(fields, fn
          {:required, name, _type} -> [{name, to_snake(name), :optional}]
          {:optional, name, _type} -> [{name, to_snake(name), :optional}]
          _ -> []
        end)

      {:group, members} ->
        Enum.flat_map(members, fn
          {:required, name, _type} -> [{name, to_snake(name), :optional}]
          {:optional, name, _type} -> [{name, to_snake(name), :optional}]
          _ -> []
        end)

      _ ->
        []
    end)
  end

  defp resolve_choice_fields(alternatives, all_rules) do
    # Resolve each alternative ref and merge all fields as optional
    Enum.flat_map(alternatives, fn
      {:ref, ref} ->
        resolve_command_fields(ref, all_rules)
        |> Enum.map(fn {json, elixir, _} -> {json, elixir, :optional} end)

      _ ->
        []
    end)
    |> Enum.uniq_by(fn {json, _, _} -> json end)
  end

  defp extract_field_defs(fields) do
    Enum.flat_map(fields, fn
      {:required, name, _type} ->
        [{name, to_snake(name), :required}]

      {:optional, name, _type} ->
        [{name, to_snake(name), :optional}]

      {:group_choice, groups} ->
        extract_field_defs_from_group_choice(groups)

      _ ->
        []
    end)
  end

  defp generate_params_body([], []) do
    "    def params(_cmd), do: %{}"
  end

  defp generate_params_body(required, []) do
    fields =
      Enum.map_join(required, ", ", fn {json_key, elixir_key, _} ->
        "#{json_key}: cmd.#{elixir_key}"
      end)

    "    def params(cmd), do: %{#{fields}}"
  end

  defp generate_params_body(required, optional) do
    required_map =
      if required == [] do
        "%{}"
      else
        fields =
          Enum.map_join(required, ", ", fn {json_key, elixir_key, _} ->
            "#{json_key}: cmd.#{elixir_key}"
          end)

        "%{#{fields}}"
      end

    optional_entries =
      Enum.map_join(optional, ",\n        ", fn {json_key, elixir_key, _} ->
        "{:#{json_key}, cmd.#{elixir_key}}"
      end)

    """
        def params(cmd) do
          optional = [
            #{optional_entries}
          ]

          Enum.reduce(optional, #{required_map}, fn
            {_key, nil}, acc -> acc
            {key, value}, acc -> Map.put(acc, key, value)
          end)
        end
    """
  end

  # ── Predicate helpers ───────────────────────────────────────────────

  defp is_command_def?({:group, members}) do
    Enum.any?(members, fn
      {:required, "method", {:string, _}} -> true
      _ -> false
    end) and
      Enum.any?(members, fn
        {:required, "params", _} -> true
        _ -> false
      end)
  end

  defp is_command_def?(_), do: false

  defp is_event_def?({:group, members}) do
    has_method =
      Enum.any?(members, fn
        {:required, "method", {:string, m}} -> not String.ends_with?(m, "Command")
        _ -> false
      end)

    has_method and is_command_def?({:group, members})
  end

  defp is_event_def?(_), do: false

  defp generate_type(name, definition) do
    short = name |> String.split(".") |> List.last()
    type_name = to_snake(short) |> String.to_atom()
    type_str = type_to_spec(definition)

    "  @type #{type_name} :: #{type_str}"
  end

  defp type_to_spec({:primitive, :text}), do: "String.t()"
  defp type_to_spec({:primitive, :text, _constraint}), do: "String.t()"
  defp type_to_spec({:primitive, :uint}), do: "non_neg_integer()"
  defp type_to_spec({:primitive, :uint, _constraint}), do: "non_neg_integer()"
  defp type_to_spec({:primitive, :int}), do: "integer()"
  defp type_to_spec({:primitive, :int, _constraint}), do: "integer()"
  defp type_to_spec({:primitive, :float}), do: "float()"
  defp type_to_spec({:primitive, :float, _constraint}), do: "float()"
  defp type_to_spec({:primitive, :bool}), do: "boolean()"
  defp type_to_spec({:primitive, :bool, _constraint}), do: "boolean()"
  defp type_to_spec({:primitive, :any}), do: "term()"
  defp type_to_spec({:primitive, :null}), do: "nil"
  defp type_to_spec({:string, _}), do: "String.t()"
  defp type_to_spec({:ref, name}), do: ref_type(name)
  defp type_to_spec({:number, n}) when is_integer(n), do: "integer()"
  defp type_to_spec({:number, n}) when is_float(n), do: "float()"
  defp type_to_spec({:range, _low, _high}), do: "integer()"
  defp type_to_spec({:range_exclusive, _low, _high}), do: "integer()"

  defp type_to_spec({:choice, items}) do
    items
    |> Enum.map(&type_to_spec/1)
    |> Enum.uniq()
    |> Enum.join(" | ")
  end

  defp type_to_spec({:array, inner, _quantifier}), do: "[#{type_to_spec(inner)}]"
  defp type_to_spec({:tuple, items}), do: "{#{Enum.map_join(items, ", ", &type_to_spec/1)}}"

  defp type_to_spec({:map, [{:fields, fields}]}) do
    field_specs =
      fields
      |> Enum.map(fn
        {:required, _key, type} -> "String.t() => #{type_to_spec(type)}"
        {:optional, _key, type} -> "optional(String.t()) => #{type_to_spec(type)}"
        {:extensible, _k, _v} -> "optional(String.t()) => term()"
        {:embed, _name} -> nil
        {:group_choice, _} -> nil
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()
      |> Enum.join(", ")

    "%{#{field_specs}}"
  end

  defp type_to_spec({:map, [{:group_choice, _groups}]}), do: "map()"
  defp type_to_spec({:map, []}), do: "map()"

  defp type_to_spec({:group, members}) do
    field_specs =
      members
      |> Enum.map(fn
        {:required, _key, type} -> "String.t() => #{type_to_spec(type)}"
        {:optional, _key, type} -> "optional(String.t()) => #{type_to_spec(type)}"
        {:embed, _name} -> nil
        {:optional_embed, _} -> nil
        _ -> nil
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()
      |> Enum.join(", ")

    "%{#{field_specs}}"
  end

  defp type_to_spec({:group_choice, _}), do: "map()"
  defp type_to_spec(_), do: "term()"

  # Well-known global types and literals
  @global_types %{
    "true" => "true",
    "false" => "false",
    "null" => "nil",
    "js-uint" => "non_neg_integer()",
    "js-int" => "integer()",
    "Extensible" => "map()"
  }

  defp ref_type(name) do
    case Map.get(@global_types, name) do
      nil ->
        if String.contains?(name, ".") do
          [mod, type] = String.split(name, ".", parts: 2)
          "Bibbidi.Types.#{to_module_name(mod)}.#{to_snake(type)}()"
        else
          # Unknown global type — use term()
          "term()"
        end

      resolved ->
        resolved
    end
  end

  defp to_snake(str) do
    str
    |> String.replace(~r/([a-z])([A-Z])/, "\\1_\\2")
    |> String.replace(~r/([A-Z]+)([A-Z][a-z])/, "\\1_\\2")
    |> String.replace("-", "_")
    |> String.downcase()
  end

  defp to_module_name(mod) do
    mod
    |> String.split(~r/[_-]/)
    |> Enum.map(&String.capitalize/1)
    |> Enum.join()
    |> then(fn
      "Browsingcontext" -> "BrowsingContext"
      "Webextension" -> "WebExtension"
      other -> other
    end)
  end
end
