# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext do
  @moduledoc """
  Type definitions for the `browsingContext` module of the WebDriver BiDi protocol.
  """

  @type browsing_context :: String.t()

  @type locator ::
          Bibbidi.Types.BrowsingContext.accessibility_locator()
          | Bibbidi.Types.BrowsingContext.css_locator()
          | Bibbidi.Types.BrowsingContext.context_locator()
          | Bibbidi.Types.BrowsingContext.inner_text_locator()
          | Bibbidi.Types.BrowsingContext.x_path_locator()

  @type accessibility_locator :: %{
          String.t() => String.t(),
          String.t() => %{optional(String.t()) => String.t()}
        }

  @type css_locator :: %{String.t() => String.t()}

  @type context_locator :: %{
          String.t() => String.t(),
          String.t() => %{String.t() => Bibbidi.Types.BrowsingContext.browsing_context()}
        }

  @type inner_text_locator :: %{
          String.t() => String.t(),
          optional(String.t()) => boolean(),
          optional(String.t()) => String.t(),
          optional(String.t()) => non_neg_integer()
        }

  @type x_path_locator :: %{String.t() => String.t()}

  @type navigation :: String.t()

  @type readiness_state :: String.t()

  @type user_prompt_type :: String.t()

  @type activate_parameters :: %{String.t() => Bibbidi.Types.BrowsingContext.browsing_context()}

  @type capture_screenshot_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => term(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.image_format(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.clip_rectangle()
        }

  @type image_format :: %{String.t() => String.t(), optional(String.t()) => integer()}

  @type clip_rectangle ::
          Bibbidi.Types.BrowsingContext.box_clip_rectangle()
          | Bibbidi.Types.BrowsingContext.element_clip_rectangle()

  @type element_clip_rectangle :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.shared_reference()
        }

  @type box_clip_rectangle :: %{String.t() => String.t(), String.t() => float()}

  @type close_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => boolean()
        }

  @type create_type :: String.t()

  @type create_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.create_type(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => boolean(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context()
        }

  @type get_tree_parameters :: %{
          optional(String.t()) => non_neg_integer(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.browsing_context()
        }

  @type handle_user_prompt_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => boolean(),
          optional(String.t()) => String.t()
        }

  @type locate_nodes_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => Bibbidi.Types.BrowsingContext.locator(),
          optional(String.t()) => term(),
          optional(String.t()) => Bibbidi.Types.Script.serialization_options(),
          optional(String.t()) => [Bibbidi.Types.Script.shared_reference()]
        }

  @type navigate_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.readiness_state()
        }

  @type print_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => boolean(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.print_margin_parameters(),
          optional(String.t()) => term(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.print_page_parameters(),
          optional(String.t()) => [non_neg_integer() | String.t()]
        }

  @type print_margin_parameters :: %{optional(String.t()) => term()}

  @type print_page_parameters :: %{optional(String.t()) => term()}

  @type reload_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => boolean(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.readiness_state()
        }

  @type set_viewport_parameters :: %{
          optional(String.t()) => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.viewport() | nil,
          optional(String.t()) => float() | nil,
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type viewport :: %{String.t() => non_neg_integer()}

  @type traverse_history_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => integer()
        }

  @type info_list :: [Bibbidi.Types.BrowsingContext.info()]

  @type info :: %{
          String.t() => Bibbidi.Types.BrowsingContext.info_list() | nil,
          String.t() => Bibbidi.Types.Browser.client_window(),
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context() | nil,
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Browser.user_context(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.browsing_context() | nil
        }

  @type base_navigation_info :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => Bibbidi.Types.BrowsingContext.navigation() | nil,
          String.t() => non_neg_integer(),
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context()
        }

  @type navigation_info :: %{}

  @type activate_result :: term()

  @type capture_screenshot_result :: %{String.t() => String.t()}

  @type close_result :: term()

  @type create_result :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context()
        }

  @type get_tree_result :: %{String.t() => Bibbidi.Types.BrowsingContext.info_list()}

  @type handle_user_prompt_result :: term()

  @type locate_nodes_result :: %{String.t() => [Bibbidi.Types.Script.node_remote_value()]}

  @type navigate_result :: %{
          String.t() => Bibbidi.Types.BrowsingContext.navigation() | nil,
          String.t() => String.t()
        }

  @type print_result :: %{String.t() => String.t()}

  @type reload_result :: Bibbidi.Types.BrowsingContext.navigate_result()

  @type set_viewport_result :: term()

  @type traverse_history_result :: term()

  @type history_updated_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => non_neg_integer(),
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context()
        }

  @type download_will_begin_params :: %{String.t() => String.t()}

  @type download_end_params :: %{}

  @type download_canceled_params :: %{String.t() => String.t()}

  @type download_complete_params :: %{String.t() => String.t(), String.t() => String.t() | nil}

  @type user_prompt_closed_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => boolean(),
          String.t() => Bibbidi.Types.BrowsingContext.user_prompt_type(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context(),
          optional(String.t()) => String.t()
        }

  @type user_prompt_opened_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => Bibbidi.Types.Session.user_prompt_handler_type(),
          String.t() => String.t(),
          String.t() => Bibbidi.Types.BrowsingContext.user_prompt_type(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context(),
          optional(String.t()) => String.t()
        }
end
