# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Browser do
  @moduledoc """
  Type definitions for the `browser` module of the WebDriver BiDi protocol.
  """

  @type client_window :: String.t()

  @type client_window_info :: %{
          String.t() => boolean(),
          String.t() => Bibbidi.Types.Browser.client_window(),
          String.t() => non_neg_integer(),
          String.t() => String.t(),
          String.t() => integer()
        }

  @type user_context :: String.t()

  @type user_context_info :: %{String.t() => Bibbidi.Types.Browser.user_context()}

  @type create_user_context_parameters :: %{
          optional(String.t()) => boolean(),
          optional(String.t()) => Bibbidi.Types.Session.proxy_configuration(),
          optional(String.t()) => Bibbidi.Types.Session.user_prompt_handler()
        }

  @type remove_user_context_parameters :: %{String.t() => Bibbidi.Types.Browser.user_context()}

  @type set_client_window_state_parameters :: %{
          String.t() => Bibbidi.Types.Browser.client_window()
        }

  @type client_window_named_state :: %{String.t() => String.t()}

  @type client_window_rect_state :: %{
          String.t() => String.t(),
          optional(String.t()) => non_neg_integer(),
          optional(String.t()) => integer()
        }

  @type set_download_behavior_parameters :: %{
          String.t() => Bibbidi.Types.Browser.download_behavior() | nil,
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type download_behavior :: %{}

  @type download_behavior_allowed :: %{String.t() => String.t()}

  @type download_behavior_denied :: %{String.t() => String.t()}

  @type close_result :: term()

  @type create_user_context_result :: Bibbidi.Types.Browser.user_context_info()

  @type get_client_windows_result :: %{String.t() => [Bibbidi.Types.Browser.client_window_info()]}

  @type get_user_contexts_result :: %{String.t() => [Bibbidi.Types.Browser.user_context_info()]}

  @type remove_user_context_result :: term()

  @type set_client_window_state_result :: Bibbidi.Types.Browser.client_window_info()

  @type set_download_behavior_result :: term()
end
