# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Emulation do
  @moduledoc """
  Type definitions for the `emulation` module of the WebDriver BiDi protocol.
  """

  @type set_forced_colors_mode_theme_override_parameters :: %{
          String.t() => Bibbidi.Types.Emulation.forced_colors_mode_theme() | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type forced_colors_mode_theme :: String.t()

  @type set_geolocation_override_parameters :: %{
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type geolocation_coordinates :: %{
          String.t() => integer(),
          optional(String.t()) => term(),
          optional(String.t()) => float() | term(),
          optional(String.t()) => integer() | term()
        }

  @type geolocation_position_error :: %{String.t() => String.t()}

  @type set_locale_override_parameters :: %{
          String.t() => String.t() | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type set_network_conditions_parameters :: %{
          String.t() => Bibbidi.Types.Emulation.network_conditions() | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type network_conditions :: Bibbidi.Types.Emulation.network_conditions_offline()

  @type network_conditions_offline :: %{String.t() => String.t()}

  @type screen_area :: %{String.t() => non_neg_integer()}

  @type set_screen_settings_override_parameters :: %{
          String.t() => Bibbidi.Types.Emulation.screen_area() | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type screen_orientation_natural :: String.t()

  @type screen_orientation_type :: String.t()

  @type screen_orientation :: %{
          String.t() => Bibbidi.Types.Emulation.screen_orientation_natural(),
          String.t() => Bibbidi.Types.Emulation.screen_orientation_type()
        }

  @type set_screen_orientation_override_parameters :: %{
          String.t() => Bibbidi.Types.Emulation.screen_orientation() | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type set_user_agent_override_parameters :: %{
          String.t() => String.t() | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type set_scripting_enabled_parameters :: %{
          String.t() => false | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type set_scrollbar_type_override_parameters :: %{
          String.t() => String.t() | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type set_timezone_override_parameters :: %{
          String.t() => String.t() | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type set_touch_override_parameters :: %{
          String.t() => term() | nil,
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type set_forced_colors_mode_theme_override_result :: term()

  @type set_geolocation_override_result :: term()

  @type set_locale_override_result :: term()

  @type set_network_conditions_result :: term()

  @type set_screen_settings_override_result :: term()

  @type set_screen_orientation_override_result :: term()

  @type set_user_agent_override_result :: term()

  @type set_scripting_enabled_result :: term()

  @type set_scrollbar_type_override_result :: term()

  @type set_timezone_override_result :: term()

  @type set_touch_override_result :: term()
end
