# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input do
  @moduledoc """
  Type definitions for the `input` module of the WebDriver BiDi protocol.
  """

  @type element_origin :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.shared_reference()
        }

  @type perform_actions_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => [Bibbidi.Types.Input.source_actions()]
        }

  @type source_actions ::
          Bibbidi.Types.Input.none_source_actions()
          | Bibbidi.Types.Input.key_source_actions()
          | Bibbidi.Types.Input.pointer_source_actions()
          | Bibbidi.Types.Input.wheel_source_actions()

  @type none_source_actions :: %{
          String.t() => String.t(),
          String.t() => [Bibbidi.Types.Input.none_source_action()]
        }

  @type none_source_action :: Bibbidi.Types.Input.pause_action()

  @type key_source_actions :: %{
          String.t() => String.t(),
          String.t() => [Bibbidi.Types.Input.key_source_action()]
        }

  @type key_source_action ::
          Bibbidi.Types.Input.pause_action()
          | Bibbidi.Types.Input.key_down_action()
          | Bibbidi.Types.Input.key_up_action()

  @type pointer_source_actions :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Input.pointer_parameters(),
          String.t() => [Bibbidi.Types.Input.pointer_source_action()]
        }

  @type pointer_type :: String.t()

  @type pointer_parameters :: %{optional(String.t()) => term()}

  @type pointer_source_action ::
          Bibbidi.Types.Input.pause_action()
          | Bibbidi.Types.Input.pointer_down_action()
          | Bibbidi.Types.Input.pointer_up_action()
          | Bibbidi.Types.Input.pointer_move_action()

  @type wheel_source_actions :: %{
          String.t() => String.t(),
          String.t() => [Bibbidi.Types.Input.wheel_source_action()]
        }

  @type wheel_source_action ::
          Bibbidi.Types.Input.pause_action() | Bibbidi.Types.Input.wheel_scroll_action()

  @type pause_action :: %{String.t() => String.t(), optional(String.t()) => non_neg_integer()}

  @type key_down_action :: %{String.t() => String.t()}

  @type key_up_action :: %{String.t() => String.t()}

  @type pointer_up_action :: %{String.t() => String.t(), String.t() => non_neg_integer()}

  @type pointer_down_action :: %{String.t() => String.t(), String.t() => non_neg_integer()}

  @type pointer_move_action :: %{
          String.t() => String.t(),
          String.t() => float(),
          optional(String.t()) => non_neg_integer(),
          optional(String.t()) => Bibbidi.Types.Input.origin()
        }

  @type wheel_scroll_action :: %{
          String.t() => String.t(),
          String.t() => integer(),
          optional(String.t()) => non_neg_integer(),
          optional(String.t()) => term()
        }

  @type pointer_common_properties :: %{
          optional(String.t()) => term(),
          optional(String.t()) => float()
        }

  @type origin :: String.t() | Bibbidi.Types.Input.element_origin()

  @type release_actions_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context()
        }

  @type set_files_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          String.t() => Bibbidi.Types.Script.shared_reference(),
          String.t() => [String.t()]
        }

  @type file_dialog_info :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context(),
          optional(String.t()) => Bibbidi.Types.Script.shared_reference(),
          String.t() => boolean()
        }

  @type perform_actions_result :: term()

  @type release_actions_result :: term()

  @type set_files_result :: term()
end
