# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Log do
  @moduledoc """
  Type definitions for the `log` module of the WebDriver BiDi protocol.
  """

  @type level :: String.t()

  @type entry ::
          Bibbidi.Types.Log.generic_log_entry()
          | Bibbidi.Types.Log.console_log_entry()
          | Bibbidi.Types.Log.javascript_log_entry()

  @type base_log_entry :: %{
          String.t() => Bibbidi.Types.Log.level(),
          String.t() => Bibbidi.Types.Script.source(),
          String.t() => String.t() | nil,
          String.t() => non_neg_integer(),
          optional(String.t()) => Bibbidi.Types.Script.stack_trace()
        }

  @type generic_log_entry :: %{String.t() => String.t()}

  @type console_log_entry :: %{
          String.t() => String.t(),
          String.t() => [Bibbidi.Types.Script.remote_value()]
        }

  @type javascript_log_entry :: %{String.t() => String.t()}
end
