# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network do
  @moduledoc """
  Type definitions for the `network` module of the WebDriver BiDi protocol.
  """

  @type auth_credentials :: %{String.t() => String.t()}

  @type bytes_value :: Bibbidi.Types.Network.string_value() | Bibbidi.Types.Network.base64value()

  @type string_value :: %{String.t() => String.t()}

  @type base64value :: %{String.t() => String.t()}

  @type collector :: String.t()

  @type collector_type :: String.t()

  @type same_site :: String.t()

  @type cookie :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Network.bytes_value(),
          String.t() => non_neg_integer(),
          String.t() => boolean(),
          String.t() => Bibbidi.Types.Network.same_site(),
          optional(String.t()) => non_neg_integer()
        }

  @type cookie_header :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Network.bytes_value()
        }

  @type data_type :: String.t()

  @type header :: %{String.t() => String.t(), String.t() => Bibbidi.Types.Network.bytes_value()}

  @type intercept :: String.t()

  @type request :: String.t()

  @type set_cookie_header :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Network.bytes_value(),
          optional(String.t()) => String.t(),
          optional(String.t()) => boolean(),
          optional(String.t()) => integer(),
          optional(String.t()) => Bibbidi.Types.Network.same_site()
        }

  @type url_pattern ::
          Bibbidi.Types.Network.url_pattern_pattern() | Bibbidi.Types.Network.url_pattern_string()

  @type url_pattern_pattern :: %{String.t() => String.t(), optional(String.t()) => String.t()}

  @type url_pattern_string :: %{String.t() => String.t()}

  @type add_data_collector_parameters :: %{
          String.t() => [Bibbidi.Types.Network.data_type()],
          String.t() => non_neg_integer(),
          optional(String.t()) => term(),
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type add_intercept_parameters :: %{
          String.t() => [Bibbidi.Types.Network.intercept_phase()],
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Network.url_pattern()]
        }

  @type intercept_phase :: String.t()

  @type continue_request_parameters :: %{
          String.t() => Bibbidi.Types.Network.request(),
          optional(String.t()) => Bibbidi.Types.Network.bytes_value(),
          optional(String.t()) => [Bibbidi.Types.Network.cookie_header()],
          optional(String.t()) => [Bibbidi.Types.Network.header()],
          optional(String.t()) => String.t()
        }

  @type continue_response_parameters :: %{
          String.t() => Bibbidi.Types.Network.request(),
          optional(String.t()) => [Bibbidi.Types.Network.set_cookie_header()],
          optional(String.t()) => Bibbidi.Types.Network.auth_credentials(),
          optional(String.t()) => [Bibbidi.Types.Network.header()],
          optional(String.t()) => String.t(),
          optional(String.t()) => non_neg_integer()
        }

  @type continue_with_auth_parameters :: %{String.t() => Bibbidi.Types.Network.request()}

  @type continue_with_auth_credentials :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Network.auth_credentials()
        }

  @type continue_with_auth_no_credentials :: %{String.t() => String.t()}

  @type disown_data_parameters :: %{
          String.t() => Bibbidi.Types.Network.data_type(),
          String.t() => Bibbidi.Types.Network.collector(),
          String.t() => Bibbidi.Types.Network.request()
        }

  @type fail_request_parameters :: %{String.t() => Bibbidi.Types.Network.request()}

  @type get_data_parameters :: %{
          String.t() => Bibbidi.Types.Network.data_type(),
          optional(String.t()) => Bibbidi.Types.Network.collector(),
          optional(String.t()) => boolean(),
          String.t() => Bibbidi.Types.Network.request()
        }

  @type provide_response_parameters :: %{
          String.t() => Bibbidi.Types.Network.request(),
          optional(String.t()) => Bibbidi.Types.Network.bytes_value(),
          optional(String.t()) => [Bibbidi.Types.Network.set_cookie_header()],
          optional(String.t()) => [Bibbidi.Types.Network.header()],
          optional(String.t()) => String.t(),
          optional(String.t()) => non_neg_integer()
        }

  @type remove_data_collector_parameters :: %{String.t() => Bibbidi.Types.Network.collector()}

  @type remove_intercept_parameters :: %{String.t() => Bibbidi.Types.Network.intercept()}

  @type set_cache_behavior_parameters :: %{
          String.t() => String.t(),
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()]
        }

  @type set_extra_headers_parameters :: %{
          String.t() => [Bibbidi.Types.Network.header()],
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type auth_challenge :: %{String.t() => String.t()}

  @type base_parameters :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context() | nil,
          String.t() => boolean(),
          String.t() => Bibbidi.Types.BrowsingContext.navigation() | nil,
          String.t() => non_neg_integer(),
          String.t() => Bibbidi.Types.Network.request_data(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context() | nil,
          optional(String.t()) => [Bibbidi.Types.Network.intercept()]
        }

  @type fetch_timing_info :: %{String.t() => float()}

  @type initiator :: %{
          optional(String.t()) => non_neg_integer(),
          optional(String.t()) => Bibbidi.Types.Network.request(),
          optional(String.t()) => Bibbidi.Types.Script.stack_trace(),
          optional(String.t()) => String.t()
        }

  @type request_data :: %{
          String.t() => Bibbidi.Types.Network.request(),
          String.t() => String.t(),
          String.t() => [Bibbidi.Types.Network.header()],
          String.t() => [Bibbidi.Types.Network.cookie()],
          String.t() => non_neg_integer(),
          String.t() => non_neg_integer() | nil,
          String.t() => String.t() | nil,
          String.t() => Bibbidi.Types.Network.fetch_timing_info()
        }

  @type response_content :: %{String.t() => non_neg_integer()}

  @type response_data :: %{
          String.t() => String.t(),
          String.t() => non_neg_integer(),
          String.t() => boolean(),
          String.t() => [Bibbidi.Types.Network.header()],
          String.t() => non_neg_integer() | nil,
          String.t() => Bibbidi.Types.Network.response_content(),
          optional(String.t()) => [Bibbidi.Types.Network.auth_challenge()]
        }

  @type add_data_collector_result :: %{String.t() => Bibbidi.Types.Network.collector()}

  @type add_intercept_result :: %{String.t() => Bibbidi.Types.Network.intercept()}

  @type continue_request_result :: term()

  @type continue_response_result :: term()

  @type continue_with_auth_result :: term()

  @type disown_data_result :: term()

  @type fail_request_result :: term()

  @type get_data_result :: %{String.t() => Bibbidi.Types.Network.bytes_value()}

  @type provide_response_result :: term()

  @type remove_data_collector_result :: term()

  @type remove_intercept_result :: term()

  @type set_cache_behavior_result :: term()

  @type set_extra_headers_result :: term()

  @type auth_required_parameters :: %{String.t() => Bibbidi.Types.Network.response_data()}

  @type before_request_sent_parameters :: %{
          optional(String.t()) => Bibbidi.Types.Network.initiator()
        }

  @type fetch_error_parameters :: %{String.t() => String.t()}

  @type response_completed_parameters :: %{String.t() => Bibbidi.Types.Network.response_data()}

  @type response_started_parameters :: %{String.t() => Bibbidi.Types.Network.response_data()}
end
