# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script do
  @moduledoc """
  Type definitions for the `script` module of the WebDriver BiDi protocol.
  """

  @type channel :: String.t()

  @type channel_value :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.channel_properties()
        }

  @type channel_properties :: %{
          String.t() => Bibbidi.Types.Script.channel(),
          optional(String.t()) => Bibbidi.Types.Script.serialization_options(),
          optional(String.t()) => Bibbidi.Types.Script.result_ownership()
        }

  @type evaluate_result ::
          Bibbidi.Types.Script.evaluate_result_success()
          | Bibbidi.Types.Script.evaluate_result_exception()

  @type evaluate_result_success :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.remote_value(),
          String.t() => Bibbidi.Types.Script.realm()
        }

  @type evaluate_result_exception :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.exception_details(),
          String.t() => Bibbidi.Types.Script.realm()
        }

  @type exception_details :: %{
          String.t() => non_neg_integer(),
          String.t() => Bibbidi.Types.Script.remote_value(),
          String.t() => Bibbidi.Types.Script.stack_trace(),
          String.t() => String.t()
        }

  @type handle :: String.t()

  @type internal_id :: String.t()

  @type local_value ::
          Bibbidi.Types.Script.remote_reference()
          | Bibbidi.Types.Script.primitive_protocol_value()
          | Bibbidi.Types.Script.channel_value()
          | Bibbidi.Types.Script.array_local_value()
          | %{}
          | Bibbidi.Types.Script.map_local_value()
          | Bibbidi.Types.Script.object_local_value()
          | Bibbidi.Types.Script.set_local_value()

  @type list_local_value :: [Bibbidi.Types.Script.local_value()]

  @type array_local_value :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.list_local_value()
        }

  @type date_local_value :: %{String.t() => String.t()}

  @type mapping_local_value :: [
          {Bibbidi.Types.Script.local_value() | String.t(), Bibbidi.Types.Script.local_value()}
        ]

  @type map_local_value :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.mapping_local_value()
        }

  @type object_local_value :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.mapping_local_value()
        }

  @type reg_exp_value :: %{String.t() => String.t(), optional(String.t()) => String.t()}

  @type reg_exp_local_value :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.reg_exp_value()
        }

  @type set_local_value :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.list_local_value()
        }

  @type preload_script :: String.t()

  @type realm :: String.t()

  @type primitive_protocol_value ::
          Bibbidi.Types.Script.undefined_value()
          | Bibbidi.Types.Script.null_value()
          | Bibbidi.Types.Script.string_value()
          | Bibbidi.Types.Script.number_value()
          | Bibbidi.Types.Script.boolean_value()
          | Bibbidi.Types.Script.big_int_value()

  @type undefined_value :: %{String.t() => String.t()}

  @type null_value :: %{String.t() => String.t()}

  @type string_value :: %{String.t() => String.t()}

  @type special_number :: String.t()

  @type number_value :: %{
          String.t() => String.t(),
          String.t() => term() | Bibbidi.Types.Script.special_number()
        }

  @type boolean_value :: %{String.t() => String.t(), String.t() => boolean()}

  @type big_int_value :: %{String.t() => String.t()}

  @type realm_type :: String.t()

  @type remote_reference ::
          Bibbidi.Types.Script.shared_reference() | Bibbidi.Types.Script.remote_object_reference()

  @type shared_reference :: %{
          String.t() => Bibbidi.Types.Script.shared_id(),
          optional(String.t()) => Bibbidi.Types.Script.handle()
        }

  @type remote_object_reference :: %{
          String.t() => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.shared_id()
        }

  @type remote_value ::
          Bibbidi.Types.Script.primitive_protocol_value()
          | Bibbidi.Types.Script.symbol_remote_value()
          | Bibbidi.Types.Script.array_remote_value()
          | Bibbidi.Types.Script.object_remote_value()
          | Bibbidi.Types.Script.function_remote_value()
          | Bibbidi.Types.Script.reg_exp_remote_value()
          | Bibbidi.Types.Script.date_remote_value()
          | Bibbidi.Types.Script.map_remote_value()
          | Bibbidi.Types.Script.set_remote_value()
          | Bibbidi.Types.Script.weak_map_remote_value()
          | Bibbidi.Types.Script.weak_set_remote_value()
          | Bibbidi.Types.Script.generator_remote_value()
          | Bibbidi.Types.Script.error_remote_value()
          | Bibbidi.Types.Script.proxy_remote_value()
          | Bibbidi.Types.Script.promise_remote_value()
          | Bibbidi.Types.Script.typed_array_remote_value()
          | Bibbidi.Types.Script.array_buffer_remote_value()
          | Bibbidi.Types.Script.node_list_remote_value()
          | Bibbidi.Types.Script.html_collection_remote_value()
          | Bibbidi.Types.Script.node_remote_value()
          | Bibbidi.Types.Script.window_proxy_remote_value()

  @type list_remote_value :: [Bibbidi.Types.Script.remote_value()]

  @type mapping_remote_value :: [
          {Bibbidi.Types.Script.remote_value() | String.t(), Bibbidi.Types.Script.remote_value()}
        ]

  @type symbol_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type array_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id(),
          optional(String.t()) => Bibbidi.Types.Script.list_remote_value()
        }

  @type object_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id(),
          optional(String.t()) => Bibbidi.Types.Script.mapping_remote_value()
        }

  @type function_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type reg_exp_remote_value :: %{
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type date_remote_value :: %{
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type map_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id(),
          optional(String.t()) => Bibbidi.Types.Script.mapping_remote_value()
        }

  @type set_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id(),
          optional(String.t()) => Bibbidi.Types.Script.list_remote_value()
        }

  @type weak_map_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type weak_set_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type generator_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type error_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type proxy_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type promise_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type typed_array_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type array_buffer_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type node_list_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id(),
          optional(String.t()) => Bibbidi.Types.Script.list_remote_value()
        }

  @type html_collection_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id(),
          optional(String.t()) => Bibbidi.Types.Script.list_remote_value()
        }

  @type node_remote_value :: %{
          String.t() => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.shared_id(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id(),
          optional(String.t()) => Bibbidi.Types.Script.node_properties()
        }

  @type node_properties :: %{
          String.t() => non_neg_integer(),
          optional(String.t()) => %{optional(String.t()) => term()},
          optional(String.t()) => [Bibbidi.Types.Script.node_remote_value()],
          optional(String.t()) => String.t(),
          optional(String.t()) => Bibbidi.Types.Script.node_remote_value() | nil
        }

  @type window_proxy_remote_value :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.window_proxy_properties(),
          optional(String.t()) => Bibbidi.Types.Script.handle(),
          optional(String.t()) => Bibbidi.Types.Script.internal_id()
        }

  @type window_proxy_properties :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context()
        }

  @type result_ownership :: String.t()

  @type serialization_options :: %{optional(String.t()) => term()}

  @type shared_id :: String.t()

  @type stack_frame :: %{String.t() => non_neg_integer(), String.t() => String.t()}

  @type stack_trace :: %{String.t() => [Bibbidi.Types.Script.stack_frame()]}

  @type realm_target :: %{String.t() => Bibbidi.Types.Script.realm()}

  @type context_target :: %{
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => String.t()
        }

  @type target :: Bibbidi.Types.Script.context_target() | Bibbidi.Types.Script.realm_target()

  @type add_preload_script_parameters :: %{
          String.t() => String.t(),
          optional(String.t()) => [Bibbidi.Types.Script.channel_value()],
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()],
          optional(String.t()) => String.t()
        }

  @type disown_parameters :: %{
          String.t() => [Bibbidi.Types.Script.handle()],
          String.t() => Bibbidi.Types.Script.target()
        }

  @type call_function_parameters :: %{
          String.t() => String.t(),
          String.t() => boolean(),
          String.t() => Bibbidi.Types.Script.target(),
          optional(String.t()) => [Bibbidi.Types.Script.local_value()],
          optional(String.t()) => Bibbidi.Types.Script.result_ownership(),
          optional(String.t()) => Bibbidi.Types.Script.serialization_options(),
          optional(String.t()) => Bibbidi.Types.Script.local_value(),
          optional(String.t()) => boolean()
        }

  @type evaluate_parameters :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Script.target(),
          String.t() => boolean(),
          optional(String.t()) => Bibbidi.Types.Script.result_ownership(),
          optional(String.t()) => Bibbidi.Types.Script.serialization_options(),
          optional(String.t()) => boolean()
        }

  @type get_realms_parameters :: %{
          optional(String.t()) => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => Bibbidi.Types.Script.realm_type()
        }

  @type remove_preload_script_parameters :: %{String.t() => Bibbidi.Types.Script.preload_script()}

  @type realm_info ::
          Bibbidi.Types.Script.window_realm_info()
          | Bibbidi.Types.Script.dedicated_worker_realm_info()
          | Bibbidi.Types.Script.shared_worker_realm_info()
          | Bibbidi.Types.Script.service_worker_realm_info()
          | Bibbidi.Types.Script.worker_realm_info()
          | Bibbidi.Types.Script.paint_worklet_realm_info()
          | Bibbidi.Types.Script.audio_worklet_realm_info()
          | Bibbidi.Types.Script.worklet_realm_info()

  @type base_realm_info :: %{String.t() => Bibbidi.Types.Script.realm(), String.t() => String.t()}

  @type window_realm_info :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context(),
          optional(String.t()) => String.t()
        }

  @type dedicated_worker_realm_info :: %{
          String.t() => String.t(),
          String.t() => [Bibbidi.Types.Script.realm()]
        }

  @type shared_worker_realm_info :: %{String.t() => String.t()}

  @type service_worker_realm_info :: %{String.t() => String.t()}

  @type worker_realm_info :: %{String.t() => String.t()}

  @type paint_worklet_realm_info :: %{String.t() => String.t()}

  @type audio_worklet_realm_info :: %{String.t() => String.t()}

  @type worklet_realm_info :: %{String.t() => String.t()}

  @type source :: %{
          String.t() => Bibbidi.Types.Script.realm(),
          optional(String.t()) => Bibbidi.Types.BrowsingContext.browsing_context(),
          optional(String.t()) => Bibbidi.Types.Browser.user_context()
        }

  @type add_preload_script_result :: %{String.t() => Bibbidi.Types.Script.preload_script()}

  @type disown_result :: term()

  @type call_function_result :: Bibbidi.Types.Script.evaluate_result()

  @type get_realms_result :: %{String.t() => [Bibbidi.Types.Script.realm_info()]}

  @type remove_preload_script_result :: term()

  @type message_parameters :: %{
          String.t() => Bibbidi.Types.Script.channel(),
          String.t() => Bibbidi.Types.Script.remote_value(),
          String.t() => Bibbidi.Types.Script.source()
        }

  @type realm_destroyed_parameters :: %{String.t() => Bibbidi.Types.Script.realm()}
end
