# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Session do
  @moduledoc """
  Type definitions for the `session` module of the WebDriver BiDi protocol.
  """

  @type capabilities_request :: %{
          optional(String.t()) => Bibbidi.Types.Session.capability_request(),
          optional(String.t()) => [Bibbidi.Types.Session.capability_request()]
        }

  @type capability_request :: %{
          optional(String.t()) => boolean(),
          optional(String.t()) => String.t(),
          optional(String.t()) => Bibbidi.Types.Session.proxy_configuration(),
          optional(String.t()) => Bibbidi.Types.Session.user_prompt_handler()
        }

  @type proxy_configuration :: map()

  @type autodetect_proxy_configuration :: %{String.t() => String.t()}

  @type direct_proxy_configuration :: %{String.t() => String.t()}

  @type manual_proxy_configuration :: %{
          String.t() => String.t(),
          optional(String.t()) => String.t(),
          optional(String.t()) => [String.t()]
        }

  @type socks_proxy_configuration :: %{String.t() => String.t(), String.t() => integer()}

  @type pac_proxy_configuration :: %{String.t() => String.t()}

  @type system_proxy_configuration :: %{String.t() => String.t()}

  @type user_prompt_handler :: %{
          optional(String.t()) => Bibbidi.Types.Session.user_prompt_handler_type()
        }

  @type user_prompt_handler_type :: String.t()

  @type subscription :: String.t()

  @type subscribe_parameters :: %{
          String.t() => [String.t()],
          optional(String.t()) => [Bibbidi.Types.BrowsingContext.browsing_context()],
          optional(String.t()) => [Bibbidi.Types.Browser.user_context()]
        }

  @type unsubscribe_by_id_request :: %{String.t() => [Bibbidi.Types.Session.subscription()]}

  @type unsubscribe_by_attributes_request :: %{String.t() => [String.t()]}

  @type new_parameters :: %{String.t() => Bibbidi.Types.Session.capabilities_request()}

  @type unsubscribe_parameters ::
          Bibbidi.Types.Session.unsubscribe_by_attributes_request()
          | Bibbidi.Types.Session.unsubscribe_by_id_request()

  @type status_result :: %{String.t() => boolean(), String.t() => String.t()}

  @type new_result :: %{
          String.t() => String.t(),
          String.t() => %{
            String.t() => boolean(),
            String.t() => String.t(),
            optional(String.t()) => Bibbidi.Types.Session.proxy_configuration(),
            optional(String.t()) => Bibbidi.Types.Session.user_prompt_handler(),
            optional(String.t()) => String.t()
          }
        }

  @type end_result :: term()

  @type subscribe_result :: %{String.t() => Bibbidi.Types.Session.subscription()}

  @type unsubscribe_result :: term()
end
