# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Storage do
  @moduledoc """
  Type definitions for the `storage` module of the WebDriver BiDi protocol.
  """

  @type partition_key :: %{optional(String.t()) => String.t()}

  @type cookie_filter :: %{
          optional(String.t()) => String.t(),
          optional(String.t()) => Bibbidi.Types.Network.bytes_value(),
          optional(String.t()) => non_neg_integer(),
          optional(String.t()) => boolean(),
          optional(String.t()) => Bibbidi.Types.Network.same_site()
        }

  @type browsing_context_partition_descriptor :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.BrowsingContext.browsing_context()
        }

  @type storage_key_partition_descriptor :: %{
          String.t() => String.t(),
          optional(String.t()) => String.t()
        }

  @type partition_descriptor ::
          Bibbidi.Types.Storage.browsing_context_partition_descriptor()
          | Bibbidi.Types.Storage.storage_key_partition_descriptor()

  @type get_cookies_parameters :: %{
          optional(String.t()) => Bibbidi.Types.Storage.cookie_filter(),
          optional(String.t()) => Bibbidi.Types.Storage.partition_descriptor()
        }

  @type partial_cookie :: %{
          String.t() => String.t(),
          String.t() => Bibbidi.Types.Network.bytes_value(),
          optional(String.t()) => String.t(),
          optional(String.t()) => boolean(),
          optional(String.t()) => Bibbidi.Types.Network.same_site(),
          optional(String.t()) => non_neg_integer()
        }

  @type set_cookie_parameters :: %{
          String.t() => Bibbidi.Types.Storage.partial_cookie(),
          optional(String.t()) => Bibbidi.Types.Storage.partition_descriptor()
        }

  @type delete_cookies_parameters :: %{
          optional(String.t()) => Bibbidi.Types.Storage.cookie_filter(),
          optional(String.t()) => Bibbidi.Types.Storage.partition_descriptor()
        }

  @type get_cookies_result :: %{
          String.t() => [Bibbidi.Types.Network.cookie()],
          String.t() => Bibbidi.Types.Storage.partition_key()
        }

  @type set_cookie_result :: %{String.t() => Bibbidi.Types.Storage.partition_key()}

  @type delete_cookies_result :: %{String.t() => Bibbidi.Types.Storage.partition_key()}
end
