# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.WebExtension do
  @moduledoc """
  Type definitions for the `webExtension` module of the WebDriver BiDi protocol.
  """

  @type extension :: String.t()

  @type install_parameters :: %{String.t() => Bibbidi.Types.WebExtension.extension_data()}

  @type extension_data ::
          Bibbidi.Types.WebExtension.extension_archive_path()
          | Bibbidi.Types.WebExtension.extension_base64encoded()
          | Bibbidi.Types.WebExtension.extension_path()

  @type extension_path :: %{String.t() => String.t()}

  @type extension_archive_path :: %{String.t() => String.t()}

  @type extension_base64encoded :: %{String.t() => String.t()}

  @type uninstall_parameters :: %{String.t() => Bibbidi.Types.WebExtension.extension()}

  @type install_result :: %{String.t() => Bibbidi.Types.WebExtension.extension()}

  @type uninstall_result :: term()
end
