# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.AddDataCollector do
  @moduledoc """
  Command struct for `network.addDataCollector`.
  """

  @enforce_keys [:data_types, :max_encoded_data_size]
  defstruct [:data_types, :max_encoded_data_size, :collector_type, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.addDataCollector"

    def params(cmd) do
      optional = [
        {:collectorType, cmd.collector_type},
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(
        optional,
        %{dataTypes: cmd.data_types, maxEncodedDataSize: cmd.max_encoded_data_size},
        fn
          {_key, nil}, acc -> acc
          {key, value}, acc -> Map.put(acc, key, value)
        end
      )
    end
  end
end
