# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.AddIntercept do
  @moduledoc """
  Command struct for `network.addIntercept`.
  """

  @enforce_keys [:phases]
  defstruct [:phases, :contexts, :url_patterns]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.addIntercept"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:urlPatterns, cmd.url_patterns}
      ]

      Enum.reduce(optional, %{phases: cmd.phases}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
