# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.ContinueRequest do
  @moduledoc """
  Command struct for `network.continueRequest`.
  """

  @enforce_keys [:request]
  defstruct [:request, :body, :cookies, :headers, :method, :url]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.continueRequest"

    def params(cmd) do
      optional = [
        {:body, cmd.body},
        {:cookies, cmd.cookies},
        {:headers, cmd.headers},
        {:method, cmd.method},
        {:url, cmd.url}
      ]

      Enum.reduce(optional, %{request: cmd.request}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
