# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.ContinueWithAuth do
  @moduledoc """
  Command struct for `network.continueWithAuth`.
  """

  @enforce_keys [:request]
  defstruct [:request]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.continueWithAuth"

    def params(cmd), do: %{request: cmd.request}
  end
end
