# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.DisownData do
  @moduledoc """
  Command struct for `network.disownData`.
  """

  @enforce_keys [:data_type, :collector, :request]
  defstruct [:data_type, :collector, :request]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.disownData"

    def params(cmd),
      do: %{dataType: cmd.data_type, collector: cmd.collector, request: cmd.request}
  end
end
