# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.GetData do
  @moduledoc """
  Command struct for `network.getData`.
  """

  @enforce_keys [:data_type, :request]
  defstruct [:data_type, :request, :collector, :disown]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.getData"

    def params(cmd) do
      optional = [
        {:collector, cmd.collector},
        {:disown, cmd.disown}
      ]

      Enum.reduce(optional, %{dataType: cmd.data_type, request: cmd.request}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
