# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.ProvideResponse do
  @moduledoc """
  Command struct for `network.provideResponse`.
  """

  @enforce_keys [:request]
  defstruct [:request, :body, :cookies, :headers, :reason_phrase, :status_code]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.provideResponse"

    def params(cmd) do
      optional = [
        {:body, cmd.body},
        {:cookies, cmd.cookies},
        {:headers, cmd.headers},
        {:reasonPhrase, cmd.reason_phrase},
        {:statusCode, cmd.status_code}
      ]

      Enum.reduce(optional, %{request: cmd.request}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
