# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.RemoveIntercept do
  @moduledoc """
  Command struct for `network.removeIntercept`.
  """

  @enforce_keys [:intercept]
  defstruct [:intercept]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.removeIntercept"

    def params(cmd), do: %{intercept: cmd.intercept}
  end
end
