# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.RemoveDataCollector do
  @moduledoc """
  Command struct for `network.removeDataCollector`.
  """

  @enforce_keys [:collector]
  defstruct [:collector]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.removeDataCollector"

    def params(cmd), do: %{collector: cmd.collector}
  end
end
