# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.SetCacheBehavior do
  @moduledoc """
  Command struct for `network.setCacheBehavior`.
  """

  @enforce_keys [:cache_behavior]
  defstruct [:cache_behavior, :contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.setCacheBehavior"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts}
      ]

      Enum.reduce(optional, %{cacheBehavior: cmd.cache_behavior}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
