# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.SetExtraHeaders do
  @moduledoc """
  Command struct for `network.setExtraHeaders`.
  """

  @enforce_keys [:headers]
  defstruct [:headers, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.setExtraHeaders"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{headers: cmd.headers}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
