# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Emulation.SetScreenSettingsOverride do
  @moduledoc """
  Command struct for `emulation.setScreenSettingsOverride`.
  """

  @enforce_keys [:screen_area]
  defstruct [:screen_area, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "emulation.setScreenSettingsOverride"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{screenArea: cmd.screen_area}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
