# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Emulation.SetLocaleOverride do
  @moduledoc """
  Command struct for `emulation.setLocaleOverride`.
  """

  @enforce_keys [:locale]
  defstruct [:locale, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "emulation.setLocaleOverride"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{locale: cmd.locale}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
