# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Emulation.SetGeolocationOverride do
  @moduledoc """
  Command struct for `emulation.setGeolocationOverride`.
  """

  defstruct [:contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "emulation.setGeolocationOverride"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
