# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Emulation.SetForcedColorsModeThemeOverride do
  @moduledoc """
  Command struct for `emulation.setForcedColorsModeThemeOverride`.
  """

  @enforce_keys [:theme]
  defstruct [:theme, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "emulation.setForcedColorsModeThemeOverride"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{theme: cmd.theme}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
