# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Emulation.SetScreenOrientationOverride do
  @moduledoc """
  Command struct for `emulation.setScreenOrientationOverride`.
  """

  @enforce_keys [:screen_orientation]
  defstruct [:screen_orientation, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "emulation.setScreenOrientationOverride"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{screenOrientation: cmd.screen_orientation}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
