# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Emulation.SetTimezoneOverride do
  @moduledoc """
  Command struct for `emulation.setTimezoneOverride`.
  """

  @enforce_keys [:timezone]
  defstruct [:timezone, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "emulation.setTimezoneOverride"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{timezone: cmd.timezone}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
