# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Emulation.SetScrollbarTypeOverride do
  @moduledoc """
  Command struct for `emulation.setScrollbarTypeOverride`.
  """

  @enforce_keys [:scrollbar_type]
  defstruct [:scrollbar_type, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "emulation.setScrollbarTypeOverride"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{scrollbarType: cmd.scrollbar_type}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
