# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Emulation.SetTouchOverride do
  @moduledoc """
  Command struct for `emulation.setTouchOverride`.
  """

  @enforce_keys [:max_touch_points]
  defstruct [:max_touch_points, :contexts, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "emulation.setTouchOverride"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{maxTouchPoints: cmd.max_touch_points}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
