# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.Close do
  @moduledoc """
  Command struct for `browser.close`.
  """

  defstruct []

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.close"

    def params(_cmd), do: %{}
  end
end
