# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.CreateUserContext do
  @moduledoc """
  Command struct for `browser.createUserContext`.
  """

  defstruct [:accept_insecure_certs, :proxy, :unhandled_prompt_behavior]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.createUserContext"

    def params(cmd) do
      optional = [
        {:acceptInsecureCerts, cmd.accept_insecure_certs},
        {:proxy, cmd.proxy},
        {:unhandledPromptBehavior, cmd.unhandled_prompt_behavior}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
