# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.GetClientWindows do
  @moduledoc """
  Command struct for `browser.getClientWindows`.
  """

  defstruct []

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.getClientWindows"

    def params(_cmd), do: %{}
  end
end
