# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.GetUserContexts do
  @moduledoc """
  Command struct for `browser.getUserContexts`.
  """

  defstruct []

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.getUserContexts"

    def params(_cmd), do: %{}
  end
end
