# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.RemoveUserContext do
  @moduledoc """
  Command struct for `browser.removeUserContext`.
  """

  @enforce_keys [:user_context]
  defstruct [:user_context]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.removeUserContext"

    def params(cmd), do: %{userContext: cmd.user_context}
  end
end
