# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.SetDownloadBehavior do
  @moduledoc """
  Command struct for `browser.setDownloadBehavior`.
  """

  @enforce_keys [:download_behavior]
  defstruct [:download_behavior, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.setDownloadBehavior"

    def params(cmd) do
      optional = [
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{downloadBehavior: cmd.download_behavior}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
