# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.SetClientWindowState do
  @moduledoc """
  Command struct for `browser.setClientWindowState`.
  """

  @enforce_keys [:client_window]
  defstruct [:client_window]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.setClientWindowState"

    def params(cmd), do: %{clientWindow: cmd.client_window}
  end
end
