# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Activate do
  @moduledoc """
  Command struct for `browsingContext.activate`.
  """

  @enforce_keys [:context]
  defstruct [:context]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.activate"

    def params(cmd), do: %{context: cmd.context}
  end
end
