# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.CaptureScreenshot do
  @moduledoc """
  Command struct for `browsingContext.captureScreenshot`.
  """

  @enforce_keys [:context]
  defstruct [:context, :origin, :format, :clip]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.captureScreenshot"

    def params(cmd) do
      optional = [
        {:origin, cmd.origin},
        {:format, cmd.format},
        {:clip, cmd.clip}
      ]

      Enum.reduce(optional, %{context: cmd.context}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
