# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Close do
  @moduledoc """
  Command struct for `browsingContext.close`.
  """

  @enforce_keys [:context]
  defstruct [:context, :prompt_unload]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.close"

    def params(cmd) do
      optional = [
        {:promptUnload, cmd.prompt_unload}
      ]

      Enum.reduce(optional, %{context: cmd.context}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
