# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Create do
  @moduledoc """
  Command struct for `browsingContext.create`.
  """

  @enforce_keys [:type]
  defstruct [:type, :reference_context, :background, :user_context]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.create"

    def params(cmd) do
      optional = [
        {:referenceContext, cmd.reference_context},
        {:background, cmd.background},
        {:userContext, cmd.user_context}
      ]

      Enum.reduce(optional, %{type: cmd.type}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
