# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.GetTree do
  @moduledoc """
  Command struct for `browsingContext.getTree`.
  """

  defstruct [:max_depth, :root]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.getTree"

    def params(cmd) do
      optional = [
        {:maxDepth, cmd.max_depth},
        {:root, cmd.root}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
