# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.HandleUserPrompt do
  @moduledoc """
  Command struct for `browsingContext.handleUserPrompt`.
  """

  @enforce_keys [:context]
  defstruct [:context, :accept, :user_text]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.handleUserPrompt"

    def params(cmd) do
      optional = [
        {:accept, cmd.accept},
        {:userText, cmd.user_text}
      ]

      Enum.reduce(optional, %{context: cmd.context}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
