# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.LocateNodes do
  @moduledoc """
  Command struct for `browsingContext.locateNodes`.
  """

  @enforce_keys [:context, :locator]
  defstruct [:context, :locator, :max_node_count, :serialization_options, :start_nodes]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.locateNodes"

    def params(cmd) do
      optional = [
        {:maxNodeCount, cmd.max_node_count},
        {:serializationOptions, cmd.serialization_options},
        {:startNodes, cmd.start_nodes}
      ]

      Enum.reduce(optional, %{context: cmd.context, locator: cmd.locator}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
