# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Navigate do
  @moduledoc """
  Command struct for `browsingContext.navigate`.
  """

  @enforce_keys [:context, :url]
  defstruct [:context, :url, :wait]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.navigate"

    def params(cmd) do
      optional = [
        {:wait, cmd.wait}
      ]

      Enum.reduce(optional, %{context: cmd.context, url: cmd.url}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
