# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Print do
  @moduledoc """
  Command struct for `browsingContext.print`.
  """

  @enforce_keys [:context]
  defstruct [
    :context,
    :background,
    :margin,
    :orientation,
    :page,
    :page_ranges,
    :scale,
    :shrink_to_fit
  ]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.print"

    def params(cmd) do
      optional = [
        {:background, cmd.background},
        {:margin, cmd.margin},
        {:orientation, cmd.orientation},
        {:page, cmd.page},
        {:pageRanges, cmd.page_ranges},
        {:scale, cmd.scale},
        {:shrinkToFit, cmd.shrink_to_fit}
      ]

      Enum.reduce(optional, %{context: cmd.context}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
