# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Reload do
  @moduledoc """
  Command struct for `browsingContext.reload`.
  """

  @enforce_keys [:context]
  defstruct [:context, :ignore_cache, :wait]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.reload"

    def params(cmd) do
      optional = [
        {:ignoreCache, cmd.ignore_cache},
        {:wait, cmd.wait}
      ]

      Enum.reduce(optional, %{context: cmd.context}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
