# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.SetViewport do
  @moduledoc """
  Command struct for `browsingContext.setViewport`.
  """

  defstruct [:context, :viewport, :device_pixel_ratio, :user_contexts]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.setViewport"

    def params(cmd) do
      optional = [
        {:context, cmd.context},
        {:viewport, cmd.viewport},
        {:devicePixelRatio, cmd.device_pixel_ratio},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
