# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.TraverseHistory do
  @moduledoc """
  Command struct for `browsingContext.traverseHistory`.
  """

  @enforce_keys [:context, :delta]
  defstruct [:context, :delta]

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.traverseHistory"

    def params(cmd), do: %{context: cmd.context, delta: cmd.delta}
  end
end
