# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.AddPreloadScript do
  @moduledoc """
  Command struct for `script.addPreloadScript`.
  """

  @enforce_keys [:function_declaration]
  defstruct [:function_declaration, :arguments, :contexts, :user_contexts, :sandbox]

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.addPreloadScript"

    def params(cmd) do
      optional = [
        {:arguments, cmd.arguments},
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts},
        {:sandbox, cmd.sandbox}
      ]

      Enum.reduce(optional, %{functionDeclaration: cmd.function_declaration}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
