# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.CallFunction do
  @moduledoc """
  Command struct for `script.callFunction`.
  """

  @enforce_keys [:function_declaration, :await_promise, :target]
  defstruct [
    :function_declaration,
    :await_promise,
    :target,
    :arguments,
    :result_ownership,
    :serialization_options,
    :this,
    :user_activation
  ]

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.callFunction"

    def params(cmd) do
      optional = [
        {:arguments, cmd.arguments},
        {:resultOwnership, cmd.result_ownership},
        {:serializationOptions, cmd.serialization_options},
        {:this, cmd.this},
        {:userActivation, cmd.user_activation}
      ]

      Enum.reduce(
        optional,
        %{
          functionDeclaration: cmd.function_declaration,
          awaitPromise: cmd.await_promise,
          target: cmd.target
        },
        fn
          {_key, nil}, acc -> acc
          {key, value}, acc -> Map.put(acc, key, value)
        end
      )
    end
  end
end
