# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.Disown do
  @moduledoc """
  Command struct for `script.disown`.
  """

  @enforce_keys [:handles, :target]
  defstruct [:handles, :target]

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.disown"

    def params(cmd), do: %{handles: cmd.handles, target: cmd.target}
  end
end
