# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.Evaluate do
  @moduledoc """
  Command struct for `script.evaluate`.
  """

  @enforce_keys [:expression, :target, :await_promise]
  defstruct [
    :expression,
    :target,
    :await_promise,
    :result_ownership,
    :serialization_options,
    :user_activation
  ]

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.evaluate"

    def params(cmd) do
      optional = [
        {:resultOwnership, cmd.result_ownership},
        {:serializationOptions, cmd.serialization_options},
        {:userActivation, cmd.user_activation}
      ]

      Enum.reduce(
        optional,
        %{expression: cmd.expression, target: cmd.target, awaitPromise: cmd.await_promise},
        fn
          {_key, nil}, acc -> acc
          {key, value}, acc -> Map.put(acc, key, value)
        end
      )
    end
  end
end
