# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.GetRealms do
  @moduledoc """
  Command struct for `script.getRealms`.
  """

  defstruct [:context, :type]

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.getRealms"

    def params(cmd) do
      optional = [
        {:context, cmd.context},
        {:type, cmd.type}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
