# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.RemovePreloadScript do
  @moduledoc """
  Command struct for `script.removePreloadScript`.
  """

  @enforce_keys [:script]
  defstruct [:script]

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.removePreloadScript"

    def params(cmd), do: %{script: cmd.script}
  end
end
